basePath: /
definitions:
  core.EventData:
    properties:
      consumed:
        type: integer
      name:
        type: string
      timestamp:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API documentation for the core service.
  title: Core Service API
  version: "1.0"
paths:
  /events-data:
    get:
      description: Returns all event consumption data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get event consumption data
      tags:
      - events
  /register:
    post:
      consumes:
      - application/json
      description: Register a number of events (calls event service)
      parameters:
      - description: Number of events to register
        in: body
        name: count
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Register events
      tags:
      - events
  /webhook:
    post:
      consumes:
      - application/json
      description: Webhook endpoint for consumer to update event consumption
      parameters:
      - description: Event data
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/core.EventData'
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Webhook to update event consumed count
      tags:
      - events
swagger: "2.0"
